version: "3"

services:
  graphdb:
    container_name: ${GRAPHDB_IMPORTRDF_CONTAINER_NAME}
    image: ontotext/graphdb:${GRAPHDB_VERSION}
    # Load all files from GRAPHDB_IMPORT_TTL_DIR in repo with configuration defined in config/graphdb-repo-config.ttl
    #entrypoint: [ "/opt/graphdb/dist/bin/importrdf", "load", "-c", "/opt/graphdb/graphdb-repo-config.ttl", "-m", "parallel", "/opt/graphdb/home/graphdb-import"]
    entrypoint: [ "/opt/graphdb/dist/bin/importrdf", "load", "-c", "/opt/graphdb/graphdb-repo-config.ttl", "-m", "parallel", "/opt/graphdb/home/graphdb-import/social_network_activity${GRAPHDB_TTL_POSTFIX}
      /opt/graphdb/home/graphdb-import/social_network_static${GRAPHDB_TTL_POSTFIX} /opt/graphdb/home/graphdb-import/social_network_person${GRAPHDB_TTL_POSTFIX}"]
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx${GRAPHDB_HEAP_SIZE} -Xms${GRAPHDB_HEAP_SIZE}
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
    volumes:
      # Change folders in the vars.sh file or directly here
      - ${GRAPHDB_CONTAINER_ROOT}:/opt/graphdb/home
      - ${GRAPHDB_IMPORT_TTL_DIR}:/opt/graphdb/home/graphdb-import
      - ${GRAPHDB_REPOSITORY_CONFIG_FILE}:/opt/graphdb/graphdb-repo-config.ttl
      - ${GRAPHDB_REPOSITORY_RULESET_FILE}:/opt/graphdb/rdfsPlus-snb-bidir.pie
